/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Sanjith
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
public class Showroom extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Showroom() {
        initComponents();
        //int num = cont;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setBounds(0,0,(int)dim.getWidth(), (int)dim.getHeight());
        //setResizable(false);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);
        //Color c = new Color(255, 255, 255, 100);
        //j11.setBackground(c);
        //j11.setOpaque(true);
        try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "sanjith23");
            //JOptionPane.showMessageDialog(null,"Connected");        
        }
        catch(ClassNotFoundException e)
        {
          JOptionPane.showMessageDialog(null,"Not Connected");
        }
       catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        c1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        tt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        j11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 900, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Registration Form");
        jLabel1.setMaximumSize(new java.awt.Dimension(114, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 384, 50));

        l1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 0, 0));
        l1.setText("Showroom name");
        getContentPane().add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 190, -1));

        l2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 0, 0));
        l2.setText("Address");
        getContentPane().add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        l3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 0, 0));
        l3.setText("City");
        getContentPane().add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 45, -1));

        l4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 0, 0));
        l4.setText("MobileNo");
        getContentPane().add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        l5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 0, 0));
        l5.setText("EmailID");
        getContentPane().add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, -1, 34));

        b1.setBackground(new java.awt.Color(255, 0, 0));
        b1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 255, 255));
        b1.setText("Register");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 690, 158, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ZIP");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 37, -1));

        t1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 142, -1));

        t2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 143, 30));

        t4.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 143, 30));

        t5.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 143, -1));

        t3.setForeground(new java.awt.Color(255, 0, 0));
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 93, 30));

        ta1.setColumns(20);
        ta1.setForeground(new java.awt.Color(255, 0, 0));
        ta1.setRows(5);
        jScrollPane2.setViewportView(ta1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 352, 33));

        c1.setForeground(new java.awt.Color(255, 0, 0));
        c1.setText("Accept terms & conditions");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 173, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 20, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Showroom ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        tt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tt1ActionPerformed(evt);
            }
        });
        getContentPane().add(tt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("State");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 60, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 140, -1));

        j11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sanjith\\Downloads\\speedometer.jpg")); // NOI18N
        getContentPane().add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
             // TODO add your handling code here:
        
        try 
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/XE", "system", "sanjith23");
            
            Statement stmt = con.createStatement(); 
            // Inserting data in database
            /*char[] s3 = p1.getPassword();
            String s4 = String.copyValueOf(s3);
            char[] s5 = p1.getPassword();
            String s6 = String.copyValueOf(s5);*/
            Pattern p = Pattern.compile("^\\d{10}$");
            Matcher m = p.matcher(t4.getText());
            Matcher m1 = p.matcher(t3.getText());
            System.out.println(m.matches());
            

             if (t1.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(null, "Enter a valid Username", "Error", JOptionPane.ERROR_MESSAGE);
               
                
            }
           
            else if (ta1.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(null, "Enter a valid Address", "Error", JOptionPane.ERROR_MESSAGE);
                
                
            }
            
            else if (t2.getText().length() == 0)
            {
                JOptionPane.showMessageDialog(null, "Enter a valid City", "Error", JOptionPane.ERROR_MESSAGE);
               
                
            }
            else  if (t3.getText().length()!= 6 && !m1.matches())
            {
                JOptionPane.showMessageDialog(null, "Enter a valid ZIP", "Error", JOptionPane.ERROR_MESSAGE);
                
                
            }
            else  if (t4.getText().length() != 10 || !m.matches())
            {
                JOptionPane.showMessageDialog(null, "Enter a valid Mobile no ", "Error", JOptionPane.ERROR_MESSAGE);
          
                
            }
            else if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", t5.getText()))) 
            {
            JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
            }

               
            else if(c1.isSelected())
            {
                String q1 = "insert into showroom values('" +tt1.getText()+"','"+t1.getText()+"',' "+ta1.getText()+"','"+jTextField2.getText()+"','"+t3.getText()+"','"+t5.getText()+"','"+t4.getText()+"','"+t2.getText()+"')";
                System.out.println(q1);
                stmt.executeUpdate(q1);
                JOptionPane.showMessageDialog(null,"Registered");
                this.dispose();
                
            }
            else if(!c1.isSelected())
            {
                JOptionPane.showMessageDialog(null,"Accept Terms and Condition");
            }

            
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Username is already taken");
            System.out.println(e);
        }
        catch(ClassNotFoundException e)
        {
          JOptionPane.showMessageDialog(null,"Not Connected");
        }

    }//GEN-LAST:event_b1ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
         if(c1.isSelected())
        {
         JOptionPane.showInternalMessageDialog(null,"On registration, we expect you to provide our showroom with an accurate and complete information of the compulsory fields.\nWe also expect you to keep the information secure, specifically access passwords and payment information. \nKindly update the information periodically to keep your account relevant.\nShowroom will guarantee with your details","Terms & Condtions",INFORMATION_MESSAGE);
        }
        //JOptionPane.showMessageDialog(new Frame(),"Hello","Terms & Condtions",INFORMATION_MESSAGE);
    }//GEN-LAST:event_c1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void tt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tt1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JCheckBox c1;
    private javax.swing.JLabel j11;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextField tt1;
    // End of variables declaration//GEN-END:variables
}
